runtime: python37
env: standard
service: ml-service
entrypoint: gunicorn -b :$PORT view:app

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic